[package]
name = "efi-agent"
version = "0.1.0"
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[dependencies]
efi-agent-core.workspace = true
ratatui = { workspace = true, features = ["crossterm"] }
crossterm = "0.29"
ctrlc = "3.5"
serde = { workspace = true, features = ["std"] }
serde_json = { workspace = true, features = ["std"] }
reqwest = { version = "0.12", default-features = false, features = ["blocking", "json", "rustls-tls"] }
fatfs = { path = "../../vendor/fatfs" }
fscommon = "0.1"
gpt = "4.1"
vt100 = "0.16.2"
arboard = { version = "3.6.1", default-features = false }
