//! Optional firmware capabilities. Detection does not grant a cryptographic trust claim.
use alloc::{format, string::String};
use uefi::{
    boot,
    proto::{
        network::ip4config2::Ip4Config2,
        rng::{Rng, RngAlgorithmType},
    },
};

#[derive(Debug)]
#[repr(transparent)]
#[uefi::proto::unsafe_protocol(uefi_raw::protocol::shell::ShellProtocol::GUID)]
struct Shell(uefi_raw::protocol::shell::ShellProtocol);

pub fn detect(startup: &str) -> String {
    let tcp4 = crate::tcp::interfaces();
    let ip4 = match boot::find_handles::<Ip4Config2>() {
        Ok(handles) => Ok(handles.len()),
        Err(error) if error.status() == uefi::Status::NOT_FOUND => Ok(0),
        Err(error) => Err(error),
    };
    let network = match (tcp4, ip4) {
        (Ok(tcp), Ok(ip)) => format!("TCP4 interfaces: {tcp}; IPv4 configuration interfaces: {ip}"),
        (Ok(tcp), Err(_)) => format!("TCP4 interfaces: {tcp}; IPv4 configuration: unavailable"),
        _ => String::from("TCP4 interface probe failed; local file tools remain available"),
    };
    let shell = match boot::find_handles::<Shell>() {
        Ok(handles) if !handles.is_empty() => {
            "UEFI Shell: protocol available; command tools pending"
        }
        Ok(_) => "UEFI Shell: unavailable (direct application boot)",
        Err(error) if error.status() == uefi::Status::NOT_FOUND => {
            "UEFI Shell: unavailable (direct application boot)"
        }
        Err(_) => "UEFI Shell: protocol probe failed",
    };
    let binding =
        crate::drivers::protocol_count(&uefi_raw::protocol::driver::DriverBindingProtocol::GUID);
    let snp = crate::drivers::protocol_count(
        &uefi_raw::protocol::network::snp::SimpleNetworkProtocol::GUID,
    );
    let mnp = crate::drivers::protocol_count(&uefi::guid!("f36ff770-a7e1-42cf-9ed2-56f0f271f44c"));
    let ip = crate::drivers::protocol_count(&uefi::guid!("c51711e7-b4bf-404a-bfb8-0a048ef1ffe4"));
    format!(
        "{network}\n{}\n{shell}\nDriver bindings: {binding}; SNP interfaces: {snp}\nMNP service bindings: {mnp}; IP4 service bindings: {ip}\n{startup}",
        probe_rng()
    )
}

fn probe_rng() -> String {
    let handles = match boot::find_handles::<Rng>() {
        Ok(handles) => handles,
        Err(error) if error.status() == uefi::Status::NOT_FOUND => {
            return String::from(
                "Cryptographic RNG: no firmware RNG protocol; TLS randomness unavailable",
            );
        }
        Err(_) => {
            return String::from(
                "Cryptographic RNG: protocol probe failed; TLS randomness unavailable",
            );
        }
    };
    if handles.is_empty() {
        return String::from(
            "Cryptographic RNG: no firmware RNG protocol; TLS randomness unavailable",
        );
    }
    // Report an explicit DRBG when available, then test the protocol default.
    let accepted = [
        (
            RngAlgorithmType::ALGORITHM_SP800_90_CTR_256,
            "SP800-90 CTR-256",
        ),
        (
            RngAlgorithmType::ALGORITHM_SP800_90_HMAC_256,
            "SP800-90 HMAC-256",
        ),
        (
            RngAlgorithmType::ALGORITHM_SP800_90_HASH_256,
            "SP800-90 HASH-256",
        ),
    ];
    for handle in handles {
        let Ok(mut rng) = boot::open_protocol_exclusive::<Rng>(handle) else {
            continue;
        };
        // Firmware capability lists are bounded. Oversized or malformed lists
        // do not trigger unbounded allocation and do not qualify a source.
        let mut algorithms = [RngAlgorithmType::ALGORITHM_RAW; 64];
        let mut bytes = core::mem::size_of_val(&algorithms);
        // SAFETY: uefi-rs Rng is repr(transparent) over RngProtocol. Bound
        // firmware's returned size before constructing a slice.
        let raw = (&mut *rng as *mut Rng).cast::<uefi_raw::protocol::rng::RngProtocol>();
        let result = unsafe { ((*raw).get_info)(raw, &mut bytes, algorithms.as_mut_ptr()) };
        if result != uefi::Status::SUCCESS
            || bytes > core::mem::size_of_val(&algorithms)
            || bytes % core::mem::size_of::<RngAlgorithmType>() != 0
        {
            continue;
        }
        let algorithms = &algorithms[..bytes / core::mem::size_of::<RngAlgorithmType>()];
        for (algorithm, name) in accepted {
            if !algorithms.contains(&algorithm) {
                continue;
            }
            let mut sample = [0; 32];
            let result = rng.get_rng(Some(algorithm), &mut sample);
            // Do not expose generated bytes. A successful call detects usable
            // protocol behavior; it cannot certify the firmware's entropy source.
            sample.fill(0);
            if result.is_ok() {
                return format!(
                    "Cryptographic RNG: {name} advertised and sample succeeded; firmware trust required"
                );
            }
        }
        let mut sample = [0; 32];
        let result = rng.get_rng(None, &mut sample);
        sample.fill(0);
        if result.is_ok() {
            return "Cryptographic RNG: firmware default succeeded; firmware trust required".into();
        }
    }
    String::from("Cryptographic RNG: no usable firmware generator; TLS randomness unavailable")
}
